# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unetwork/core/types.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='unetwork/core/types.proto',
  package='unetwork',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19unetwork/core/types.proto\x12\x08unetwork\"\x1d\n\x10\x44iscreteInterval\x12\t\n\x01n\x18\x01 \x01(\x05\";\n\x12\x43ontinuousInterval\x12\x11\n\tlow_value\x18\x01 \x01(\x01\x12\x12\n\nhigh_value\x18\x02 \x01(\x01\"U\n\rPhysicalParam\x12\n\n\x02id\x18\x01 \x01(\t\x12)\n\x04type\x18\x02 \x01(\x0e\x32\x1b.unetwork.PhysicalValueType\x12\r\n\x05value\x18\x03 \x01(\x02*3\n\rParameterType\x12\x0f\n\x0bPT_DISCRETE\x10\x00\x12\x11\n\rPT_CONTINUOUS\x10\x01*\x86\x01\n\x11PhysicalValueType\x12\r\n\tPV_NOTYPE\x10\x00\x12\x0c\n\x08PV_STATE\x10\x01\x12\x0f\n\x0bPV_PRESSURE\x10\x02\x12\x12\n\x0ePV_TEMPERATURE\x10\x03\x12\x0e\n\nPV_DENSITY\x10\x04\x12\r\n\tPV_VOLUME\x10\x05\x12\x10\n\x0cPV_FREQUENCY\x10\x06\x62\x06proto3')
)

_PARAMETERTYPE = _descriptor.EnumDescriptor(
  name='ParameterType',
  full_name='unetwork.ParameterType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PT_DISCRETE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PT_CONTINUOUS', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=218,
  serialized_end=269,
)
_sym_db.RegisterEnumDescriptor(_PARAMETERTYPE)

ParameterType = enum_type_wrapper.EnumTypeWrapper(_PARAMETERTYPE)
_PHYSICALVALUETYPE = _descriptor.EnumDescriptor(
  name='PhysicalValueType',
  full_name='unetwork.PhysicalValueType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PV_NOTYPE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PV_STATE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PV_PRESSURE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PV_TEMPERATURE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PV_DENSITY', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PV_VOLUME', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PV_FREQUENCY', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=272,
  serialized_end=406,
)
_sym_db.RegisterEnumDescriptor(_PHYSICALVALUETYPE)

PhysicalValueType = enum_type_wrapper.EnumTypeWrapper(_PHYSICALVALUETYPE)
PT_DISCRETE = 0
PT_CONTINUOUS = 1
PV_NOTYPE = 0
PV_STATE = 1
PV_PRESSURE = 2
PV_TEMPERATURE = 3
PV_DENSITY = 4
PV_VOLUME = 5
PV_FREQUENCY = 6



_DISCRETEINTERVAL = _descriptor.Descriptor(
  name='DiscreteInterval',
  full_name='unetwork.DiscreteInterval',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n', full_name='unetwork.DiscreteInterval.n', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=68,
)


_CONTINUOUSINTERVAL = _descriptor.Descriptor(
  name='ContinuousInterval',
  full_name='unetwork.ContinuousInterval',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='low_value', full_name='unetwork.ContinuousInterval.low_value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='high_value', full_name='unetwork.ContinuousInterval.high_value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=129,
)


_PHYSICALPARAM = _descriptor.Descriptor(
  name='PhysicalParam',
  full_name='unetwork.PhysicalParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='unetwork.PhysicalParam.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='unetwork.PhysicalParam.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='unetwork.PhysicalParam.value', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=216,
)

_PHYSICALPARAM.fields_by_name['type'].enum_type = _PHYSICALVALUETYPE
DESCRIPTOR.message_types_by_name['DiscreteInterval'] = _DISCRETEINTERVAL
DESCRIPTOR.message_types_by_name['ContinuousInterval'] = _CONTINUOUSINTERVAL
DESCRIPTOR.message_types_by_name['PhysicalParam'] = _PHYSICALPARAM
DESCRIPTOR.enum_types_by_name['ParameterType'] = _PARAMETERTYPE
DESCRIPTOR.enum_types_by_name['PhysicalValueType'] = _PHYSICALVALUETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DiscreteInterval = _reflection.GeneratedProtocolMessageType('DiscreteInterval', (_message.Message,), {
  'DESCRIPTOR' : _DISCRETEINTERVAL,
  '__module__' : 'unetwork.core.types_pb2'
  # @@protoc_insertion_point(class_scope:unetwork.DiscreteInterval)
  })
_sym_db.RegisterMessage(DiscreteInterval)

ContinuousInterval = _reflection.GeneratedProtocolMessageType('ContinuousInterval', (_message.Message,), {
  'DESCRIPTOR' : _CONTINUOUSINTERVAL,
  '__module__' : 'unetwork.core.types_pb2'
  # @@protoc_insertion_point(class_scope:unetwork.ContinuousInterval)
  })
_sym_db.RegisterMessage(ContinuousInterval)

PhysicalParam = _reflection.GeneratedProtocolMessageType('PhysicalParam', (_message.Message,), {
  'DESCRIPTOR' : _PHYSICALPARAM,
  '__module__' : 'unetwork.core.types_pb2'
  # @@protoc_insertion_point(class_scope:unetwork.PhysicalParam)
  })
_sym_db.RegisterMessage(PhysicalParam)


# @@protoc_insertion_point(module_scope)
