#include "pch.h"
// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: energyplatform/core/env_service.proto

#include "energyplatform/core/env_service.pb.h"
#include "energyplatform/core/env_service.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace energyplatform {

static const char* EnvService_method_names[] = {
  "/energyplatform.EnvService/LoadData",
  "/energyplatform.EnvService/SetCurrentTask",
  "/energyplatform.EnvService/GetEnvDescription",
  "/energyplatform.EnvService/GetOptimizationParams",
  "/energyplatform.EnvService/Reset",
  "/energyplatform.EnvService/Step",
  "/energyplatform.EnvService/Stop",
};

std::unique_ptr< EnvService::Stub> EnvService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< EnvService::Stub> stub(new EnvService::Stub(channel));
  return stub;
}

EnvService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_LoadData_(EnvService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetCurrentTask_(EnvService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetEnvDescription_(EnvService_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetOptimizationParams_(EnvService_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Reset_(EnvService_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Step_(EnvService_method_names[5], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Stop_(EnvService_method_names[6], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status EnvService::Stub::LoadData(::grpc::ClientContext* context, const ::energyplatform::LoadDataRequest& request, ::energyplatform::LoadDataResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_LoadData_, context, request, response);
}

void EnvService::Stub::experimental_async::LoadData(::grpc::ClientContext* context, const ::energyplatform::LoadDataRequest* request, ::energyplatform::LoadDataResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_LoadData_, context, request, response, std::move(f));
}

void EnvService::Stub::experimental_async::LoadData(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::energyplatform::LoadDataResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_LoadData_, context, request, response, std::move(f));
}

void EnvService::Stub::experimental_async::LoadData(::grpc::ClientContext* context, const ::energyplatform::LoadDataRequest* request, ::energyplatform::LoadDataResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_LoadData_, context, request, response, reactor);
}

void EnvService::Stub::experimental_async::LoadData(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::energyplatform::LoadDataResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_LoadData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::energyplatform::LoadDataResponse>* EnvService::Stub::AsyncLoadDataRaw(::grpc::ClientContext* context, const ::energyplatform::LoadDataRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::energyplatform::LoadDataResponse>::Create(channel_.get(), cq, rpcmethod_LoadData_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::energyplatform::LoadDataResponse>* EnvService::Stub::PrepareAsyncLoadDataRaw(::grpc::ClientContext* context, const ::energyplatform::LoadDataRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::energyplatform::LoadDataResponse>::Create(channel_.get(), cq, rpcmethod_LoadData_, context, request, false);
}

::grpc::Status EnvService::Stub::SetCurrentTask(::grpc::ClientContext* context, const ::energyplatform::SetCurrentTaskRequest& request, ::energyplatform::SetCurrentTaskResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SetCurrentTask_, context, request, response);
}

void EnvService::Stub::experimental_async::SetCurrentTask(::grpc::ClientContext* context, const ::energyplatform::SetCurrentTaskRequest* request, ::energyplatform::SetCurrentTaskResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SetCurrentTask_, context, request, response, std::move(f));
}

void EnvService::Stub::experimental_async::SetCurrentTask(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::energyplatform::SetCurrentTaskResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SetCurrentTask_, context, request, response, std::move(f));
}

void EnvService::Stub::experimental_async::SetCurrentTask(::grpc::ClientContext* context, const ::energyplatform::SetCurrentTaskRequest* request, ::energyplatform::SetCurrentTaskResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SetCurrentTask_, context, request, response, reactor);
}

void EnvService::Stub::experimental_async::SetCurrentTask(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::energyplatform::SetCurrentTaskResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SetCurrentTask_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::energyplatform::SetCurrentTaskResponse>* EnvService::Stub::AsyncSetCurrentTaskRaw(::grpc::ClientContext* context, const ::energyplatform::SetCurrentTaskRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::energyplatform::SetCurrentTaskResponse>::Create(channel_.get(), cq, rpcmethod_SetCurrentTask_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::energyplatform::SetCurrentTaskResponse>* EnvService::Stub::PrepareAsyncSetCurrentTaskRaw(::grpc::ClientContext* context, const ::energyplatform::SetCurrentTaskRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::energyplatform::SetCurrentTaskResponse>::Create(channel_.get(), cq, rpcmethod_SetCurrentTask_, context, request, false);
}

::grpc::Status EnvService::Stub::GetEnvDescription(::grpc::ClientContext* context, const ::energyplatform::GetEnvDescriptionRequest& request, ::energyplatform::GetEnvDescriptionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetEnvDescription_, context, request, response);
}

void EnvService::Stub::experimental_async::GetEnvDescription(::grpc::ClientContext* context, const ::energyplatform::GetEnvDescriptionRequest* request, ::energyplatform::GetEnvDescriptionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetEnvDescription_, context, request, response, std::move(f));
}

void EnvService::Stub::experimental_async::GetEnvDescription(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::energyplatform::GetEnvDescriptionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetEnvDescription_, context, request, response, std::move(f));
}

void EnvService::Stub::experimental_async::GetEnvDescription(::grpc::ClientContext* context, const ::energyplatform::GetEnvDescriptionRequest* request, ::energyplatform::GetEnvDescriptionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetEnvDescription_, context, request, response, reactor);
}

void EnvService::Stub::experimental_async::GetEnvDescription(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::energyplatform::GetEnvDescriptionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetEnvDescription_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::energyplatform::GetEnvDescriptionResponse>* EnvService::Stub::AsyncGetEnvDescriptionRaw(::grpc::ClientContext* context, const ::energyplatform::GetEnvDescriptionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::energyplatform::GetEnvDescriptionResponse>::Create(channel_.get(), cq, rpcmethod_GetEnvDescription_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::energyplatform::GetEnvDescriptionResponse>* EnvService::Stub::PrepareAsyncGetEnvDescriptionRaw(::grpc::ClientContext* context, const ::energyplatform::GetEnvDescriptionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::energyplatform::GetEnvDescriptionResponse>::Create(channel_.get(), cq, rpcmethod_GetEnvDescription_, context, request, false);
}

::grpc::Status EnvService::Stub::GetOptimizationParams(::grpc::ClientContext* context, const ::energyplatform::GetOptimizationParamsRequest& request, ::energyplatform::GetOptimizationParamsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetOptimizationParams_, context, request, response);
}

void EnvService::Stub::experimental_async::GetOptimizationParams(::grpc::ClientContext* context, const ::energyplatform::GetOptimizationParamsRequest* request, ::energyplatform::GetOptimizationParamsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetOptimizationParams_, context, request, response, std::move(f));
}

void EnvService::Stub::experimental_async::GetOptimizationParams(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::energyplatform::GetOptimizationParamsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetOptimizationParams_, context, request, response, std::move(f));
}

void EnvService::Stub::experimental_async::GetOptimizationParams(::grpc::ClientContext* context, const ::energyplatform::GetOptimizationParamsRequest* request, ::energyplatform::GetOptimizationParamsResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetOptimizationParams_, context, request, response, reactor);
}

void EnvService::Stub::experimental_async::GetOptimizationParams(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::energyplatform::GetOptimizationParamsResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetOptimizationParams_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::energyplatform::GetOptimizationParamsResponse>* EnvService::Stub::AsyncGetOptimizationParamsRaw(::grpc::ClientContext* context, const ::energyplatform::GetOptimizationParamsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::energyplatform::GetOptimizationParamsResponse>::Create(channel_.get(), cq, rpcmethod_GetOptimizationParams_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::energyplatform::GetOptimizationParamsResponse>* EnvService::Stub::PrepareAsyncGetOptimizationParamsRaw(::grpc::ClientContext* context, const ::energyplatform::GetOptimizationParamsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::energyplatform::GetOptimizationParamsResponse>::Create(channel_.get(), cq, rpcmethod_GetOptimizationParams_, context, request, false);
}

::grpc::Status EnvService::Stub::Reset(::grpc::ClientContext* context, const ::energyplatform::ResetRequest& request, ::energyplatform::ResetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Reset_, context, request, response);
}

void EnvService::Stub::experimental_async::Reset(::grpc::ClientContext* context, const ::energyplatform::ResetRequest* request, ::energyplatform::ResetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Reset_, context, request, response, std::move(f));
}

void EnvService::Stub::experimental_async::Reset(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::energyplatform::ResetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Reset_, context, request, response, std::move(f));
}

void EnvService::Stub::experimental_async::Reset(::grpc::ClientContext* context, const ::energyplatform::ResetRequest* request, ::energyplatform::ResetResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Reset_, context, request, response, reactor);
}

void EnvService::Stub::experimental_async::Reset(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::energyplatform::ResetResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Reset_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::energyplatform::ResetResponse>* EnvService::Stub::AsyncResetRaw(::grpc::ClientContext* context, const ::energyplatform::ResetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::energyplatform::ResetResponse>::Create(channel_.get(), cq, rpcmethod_Reset_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::energyplatform::ResetResponse>* EnvService::Stub::PrepareAsyncResetRaw(::grpc::ClientContext* context, const ::energyplatform::ResetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::energyplatform::ResetResponse>::Create(channel_.get(), cq, rpcmethod_Reset_, context, request, false);
}

::grpc::Status EnvService::Stub::Step(::grpc::ClientContext* context, const ::energyplatform::StepRequest& request, ::energyplatform::StepResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Step_, context, request, response);
}

void EnvService::Stub::experimental_async::Step(::grpc::ClientContext* context, const ::energyplatform::StepRequest* request, ::energyplatform::StepResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Step_, context, request, response, std::move(f));
}

void EnvService::Stub::experimental_async::Step(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::energyplatform::StepResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Step_, context, request, response, std::move(f));
}

void EnvService::Stub::experimental_async::Step(::grpc::ClientContext* context, const ::energyplatform::StepRequest* request, ::energyplatform::StepResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Step_, context, request, response, reactor);
}

void EnvService::Stub::experimental_async::Step(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::energyplatform::StepResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Step_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::energyplatform::StepResponse>* EnvService::Stub::AsyncStepRaw(::grpc::ClientContext* context, const ::energyplatform::StepRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::energyplatform::StepResponse>::Create(channel_.get(), cq, rpcmethod_Step_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::energyplatform::StepResponse>* EnvService::Stub::PrepareAsyncStepRaw(::grpc::ClientContext* context, const ::energyplatform::StepRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::energyplatform::StepResponse>::Create(channel_.get(), cq, rpcmethod_Step_, context, request, false);
}

::grpc::Status EnvService::Stub::Stop(::grpc::ClientContext* context, const ::energyplatform::StopRequest& request, ::energyplatform::StopResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Stop_, context, request, response);
}

void EnvService::Stub::experimental_async::Stop(::grpc::ClientContext* context, const ::energyplatform::StopRequest* request, ::energyplatform::StopResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Stop_, context, request, response, std::move(f));
}

void EnvService::Stub::experimental_async::Stop(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::energyplatform::StopResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Stop_, context, request, response, std::move(f));
}

void EnvService::Stub::experimental_async::Stop(::grpc::ClientContext* context, const ::energyplatform::StopRequest* request, ::energyplatform::StopResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Stop_, context, request, response, reactor);
}

void EnvService::Stub::experimental_async::Stop(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::energyplatform::StopResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Stop_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::energyplatform::StopResponse>* EnvService::Stub::AsyncStopRaw(::grpc::ClientContext* context, const ::energyplatform::StopRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::energyplatform::StopResponse>::Create(channel_.get(), cq, rpcmethod_Stop_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::energyplatform::StopResponse>* EnvService::Stub::PrepareAsyncStopRaw(::grpc::ClientContext* context, const ::energyplatform::StopRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::energyplatform::StopResponse>::Create(channel_.get(), cq, rpcmethod_Stop_, context, request, false);
}

EnvService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EnvService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EnvService::Service, ::energyplatform::LoadDataRequest, ::energyplatform::LoadDataResponse>(
          std::mem_fn(&EnvService::Service::LoadData), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EnvService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EnvService::Service, ::energyplatform::SetCurrentTaskRequest, ::energyplatform::SetCurrentTaskResponse>(
          std::mem_fn(&EnvService::Service::SetCurrentTask), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EnvService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EnvService::Service, ::energyplatform::GetEnvDescriptionRequest, ::energyplatform::GetEnvDescriptionResponse>(
          std::mem_fn(&EnvService::Service::GetEnvDescription), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EnvService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EnvService::Service, ::energyplatform::GetOptimizationParamsRequest, ::energyplatform::GetOptimizationParamsResponse>(
          std::mem_fn(&EnvService::Service::GetOptimizationParams), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EnvService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EnvService::Service, ::energyplatform::ResetRequest, ::energyplatform::ResetResponse>(
          std::mem_fn(&EnvService::Service::Reset), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EnvService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EnvService::Service, ::energyplatform::StepRequest, ::energyplatform::StepResponse>(
          std::mem_fn(&EnvService::Service::Step), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EnvService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EnvService::Service, ::energyplatform::StopRequest, ::energyplatform::StopResponse>(
          std::mem_fn(&EnvService::Service::Stop), this)));
}

EnvService::Service::~Service() {
}

::grpc::Status EnvService::Service::LoadData(::grpc::ServerContext* context, const ::energyplatform::LoadDataRequest* request, ::energyplatform::LoadDataResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EnvService::Service::SetCurrentTask(::grpc::ServerContext* context, const ::energyplatform::SetCurrentTaskRequest* request, ::energyplatform::SetCurrentTaskResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EnvService::Service::GetEnvDescription(::grpc::ServerContext* context, const ::energyplatform::GetEnvDescriptionRequest* request, ::energyplatform::GetEnvDescriptionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EnvService::Service::GetOptimizationParams(::grpc::ServerContext* context, const ::energyplatform::GetOptimizationParamsRequest* request, ::energyplatform::GetOptimizationParamsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EnvService::Service::Reset(::grpc::ServerContext* context, const ::energyplatform::ResetRequest* request, ::energyplatform::ResetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EnvService::Service::Step(::grpc::ServerContext* context, const ::energyplatform::StepRequest* request, ::energyplatform::StepResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EnvService::Service::Stop(::grpc::ServerContext* context, const ::energyplatform::StopRequest* request, ::energyplatform::StopResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace energyplatform

